url=https://www.saucedemo.com
username=standard_user
password=secret_sauce
browserName=chrome
firstname=Ibrahim
lastname=Ali
postalCode=1612
checkoutUrlStepOne = https://www.saucedemo.com/checkout-step-one.html
checkoutUrlStepTwo = https://www.saucedemo.com/checkout-step-two.html
completeUrl = https://www.saucedemo.com/checkout-complete.html
